import dotenv from "dotenv"
dotenv.config({path:"../.env"})

export const { PORT , SECRET_KEY , DATABASE_URL , 
    JWT_ACCESS_SECRET , JWT_REFRESH_SECRET , MAIN_DOMAIN,
    JWT_ACCESS_EXPIRES_IN,JWT_REFRESH_EXPIRES_IN, JWT_ALGO,
    UPLOAD_ROOT,UPLOAD_PUBLIC_BASE, SALT_ROUND,CORNERAUTHSECRET,CORNERTECHROUND} = process.env